### ISSUE TITLE
Boilerplate for liftM2 through liftM22 (and liftA*)

### ISSUE THREAD

**Issue by wheaties** [wheaties/AutoLifts#25]
Haskell has up to liftM5. Scala tends to go to 22. I've got all of 3. Writing it by hand a bit of a PITA. Boilerplate.scala a la Shapeless or Cats.

**Comment by frosforever** [comment]
@wheaties I'm on it

**Comment by wheaties** [comment]
I've figured out LiftA\* boilerplate but #19 and Cats support using Miles' export-hook may prevent past arity 5, basically on par with Haskell.

**Comment by frosforever** [comment]
@wheaties I don't know enough about export-hook. What seems to be the issue?

**Comment by wheaties** [comment]
Worries about compilation speed. Miles asked me to cap it at a lower arity until this can be quantified. Hence, I'll be able to keep parity with haskell but not with all function arity.

**Comment by frosforever** [comment]
would that mean [maxArity](https://github.com/wheaties/AutoLifts/blob/e2f00947cc55386983f13f7a54352b72ed09ac0c/project/Boilerplate.scala#L46) should be 6 (n + 1 as you need one extra DFunction)?
