### ISSUE TITLE
Research lifting natural transformations

### ISSUE THREAD

**Issue by wheaties** [wheaties/AutoLifts#44]
If I have an type such as `F[G[H[A]]]` and a function of the form `H ~> M` why can't they lift? For reference, see [NaturalTransform](https://github.com/scalaz/scalaz/blob/series/7.3.x/core/src/main/scala/scalaz/NaturalTransformation.scala#L14-L24) of Scalaz.

It seems naively possible to construct the implicit proof as follows:

``` scala
implicit def nat[F[_], G[_], H[_], A](implicit fn: Functor[F]) = 
  new Liftmap[F[G[A]], G ~> H]{
    type Out = F[H[A]]

    def apply(fga: F[G[A]], nt: G ~> H) = fn.map(fga){ ga: G[A] => nt(ga) }
```

**Comment by Jentsch** [comment]
I played around with natural transformations: [Branch WIP-Scalaz-NaturalTransformation](https://github.com/Jentsch/AutoLifts/tree/WIP-Scalaz-NaturalTransformation)

**Comment by wheaties** [comment]
@Jentsch in your opinion, do you think we should also support direct application of the function to `F[_]` instead of requiring a nested structure?

**Comment by Jentsch** [comment]
I'm not sure. It reduces code duplication and leads to valid code like (1).autoMap(i: Int = i \* 2) == 2 for the not poly case. This behaviour is maybe unexpected, but also more generic. I tend to a allow direct application, also for normal functions. But this is only my optinion. How do you @wheaties see this?
