### ISSUE TITLE
LiftMapM

### ISSUE THREAD

**Issue by wheaties** [wheaties/AutoLifts#56]
Take a look at Traversable's [mapM](https://hackage.haskell.org/package/base-4.8.2.0/docs/Data-Traversable.html#v:mapM) function. This is, in many ways, a combination of both `flatMap` and `sequence` rolled into one. Seems like it's the thing you want and need @Jentsch.

``` scala
val item: List[Int] = //...
val out: Option[List[Int]] = item liftMapM { x: Int => if(x > 0) Some(x) else None }
```

**Comment by Jentsch** [comment]
I'm not sure. This looks like `traverse` except it requires not an Applicative but a Monad. Where is the `flat` part? I thought of something like:

``` scala
val item: Option[List[Int]] = //...
val out: Option[List[Int]] = item liftFlatMapM { x: Int =>
  if(x > 0) Some(x) else None
}
```

**Comment by wheaties** [comment]
You're right. For some reason I thought it was opposite but it's not. Closing.
